version: '3.7'
services:
  #Cloudservices
  #Spring Cloud Config
  config-service:
    image: rivasb/rivasb-config:v1
    container_name: config
    restart: unless-stopped
    hostname: config
    networks:
      - tteams_internal
    ports:
      - "8081:8081"
  # Netflix Eureka Server
  registry-service:
    image: rivasb/rivasb-registry:v1
    container_name: registry
    restart: unless-stopped
    hostname: registry
    depends_on:
      - config-service
    networks:
      - tteams_internal
    ports:
      - "8099:8099"
  # Spring Cloud Gateway
  gateway-service:
    image: rivasb/rivasb-gateway:v1
    container_name: gateway
    restart: unless-stopped
    hostname: gateway
    depends_on:
      - config-service
      - registry-service
    networks:
      - tteams_internal
      - ev_bridge
    ports:
      - "8091:8091"
  # Microservices
  # waste-center-auth
  waste-center-auth-service:
    image: rivasb/rivasb-waste-center-auth:v1
    container_name: identity
    restart: unless-stopped
    hostname: identity
    depends_on:
      - config-service
      - registry-service
      - gateway-service
    networks:
      - tteams_internal
    ports:
      - "8085:8085"
  # waste-management
  waste-management-service:
    image: rivasb/rivasb-waste-management:v1
    container_name: project
    restart: unless-stopped
    hostname: project
    depends_on:
      - config-service
      - registry-service
      - gateway-service
    networks:
      - tteams_internal
    ports:
      - "8084:8084"
networks:
  tteams_internal:
  ev_bridge:
    driver: bridge
